### ISSUE TITLE
Example Issue to add content

### ISSUE THREAD

**Issue by madsailor** [madsailor/CrowdSourcedScience#1]
I don't want to fork, pull, edit, commit, push, and send a pull request for just a line or two that I would like to contribute.  Instead I will ask you to please add 
"KerbinSrfLandedGrasslands = As you wander through the grasslands of Kerbin you contemplate the awesomeness and complexity of Github." 
to planets/kerbin/grasslands/eva.cfg. I still had to create a github account, but this is far simpler, so it makes me more likely to actually contribute.

**Comment by DuoDex** [comment]
Good idea.

**Comment by harryyoung** [comment]
Aye
